kind: pipeline
name: build

steps:
- name: hello
  image: alpine:3.8
  commands:
  - echo hello
  - sleep 5
  
- name: world
  image: alpine:3.8
  commands:
  - echo world
  - sleep 60
  - exit 78
  
- name: bonjour
  image: alpine:3.8
  commands:
  - echo bonjour
  - sleep 5

- name: monde
  image: alpine:3.8
  commands:
  - echo Hello World!!!
  - sleep 60

services:
- name: redis
  image: redis
